### ISSUE TITLE
Copy over global styles

### ISSUE THREAD

**Issue by Briggybros** [Briggybros/react-douglas#1]

**Comment by bkazi** [comment]
Could this just be "left as an exercise for the reader"?
eg. https://github.com/Briggybros/styled-window-portal

**Comment by Briggybros** [comment]
Maybe it should be implemented as a separate dep, but I think the functionality should be easily provided in some way or another.

**Comment by Briggybros** [comment]
The process of copying styles from one document to another is out of scope for this project.
